---
- name: sysctl role
  tags:
    - sysctl
  block:

  # assert
  - name: Assertions for msmtp-aliases
    ansible.builtin.assert:
      that:
      - sysctl_config_vars is not string 
      - sysctl_config_vars is iterable 
      - sysctl_config_vars is mapping

  # template
  - name: Template /etc/sysctl.d/99-ansible.conf
    when: sysctl_config_vars | length > 0
    become: true
    ansible.builtin.template:
      src: sysctl-ansible.conf.j2
      dest: /etc/sysctl.d/99-ansible.conf
      owner: root
      group: root
      mode: '0644'

  # copy
  - when: sysctl_config_files | length > 0
    name: Copy config files
    loop: "{{ sysctl_config_files }}"
    become: true
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/sysctl.d/
      owner: root
      group: root
      mode: u=rw,g=r,o=r